### ISSUE TITLE
Master Issue: Tracking Design Improvements

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#20]
## Ready for Dev

- [x] [Update Google Fonts in Caseflow Commons](https://github.com/department-of-veterans-affairs/caseflow-commons/issues/9)
- [x] [Fix Favicons](https://github.com/department-of-veterans-affairs/caseflow/issues/509)
- [x] [Make all black text USWDS gray-dark](https://github.com/department-of-veterans-affairs/caseflow-commons/issues/12)
- [x] [Make sure app branding is consistent across all apps](https://github.com/department-of-veterans-affairs/caseflow-commons/issues/19) 
  - Padding between logo and app name is consistent
  - Padding between first and second words of app name is consistent
  - colors/weights of app name is consistent
  - margins/padding in nav bar should be consistent across apps
  - [make sure hover states and active states are correct](https://github.com/department-of-veterans-affairs/caseflow-commons/issues/11)
- [x] [Make sure "brand logo" in nav bar is unique per app
   - Dispatch should be purple
   - Feedback should be turqoise
   - eFolder Express hsould be organge
   - Certification should be blue
- [x] [Clean up footer in Caseflow Apps](https://github.com/department-of-veterans-affairs/caseflow-commons/issues/22)
- [x] [Fix FAQ Pages](https://github.com/department-of-veterans-affairs/caseflow-commons/issues/25)
- [x] [Required Labels](https://github.com/department-of-veterans-affairs/caseflow-commons/issues/24)
   - For boxes, right align "Required" label
   - Don't add parentheses around "Required" label (for checkbox/radio questions)
   - Keep at least 2px spacing b/t "Required" label and text to the left (for checkbox/radio questions)
   - Left align "required" label (for checkbox/radio questions)
   - Don't use colons at the end of questions or labels
- [x] [Fix loading buttons in eFolder express](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/327)
- [x] [Fix off-by-one pixel on tabs](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/328)
- [x] [Add chevron to efolder express history table](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/329)
- [x] [Remove underlines from `abbr` tags](https://github.com/department-of-veterans-affairs/caseflow-commons/issues/21)

## To Design

- [x] ~Re Design Navigation Dropdown Menu~ Moved up to ready for Develpment
   - The profile dropdown should be shifted to the left 33 px from the edge of the first letter of the first name
   - The type color also seems a shade or two lighter. No RGB provided in Style Guide
   - Not in style guide, but when you click the profile in the current eFolder Express the borders of the profile name turns to a blue. Correct?
   - [Dropdown menu options should not be links] (https://github.com/department-of-veterans-affairs/caseflow-commons/issues/13)
- [ ] Error states
   - Notes should be consistent 
   - Make italic
   - preface with "Note:" 
   - CTAs in errors
- [x] ~Loading button~ added above
   - Should be disabled and show loading indicator inside of it
- [ ] Create a real date picker
   - Should support text input 
   - Should support calendar selection
- [ ] Dynamic Search Dropdown
   - The style guide shows dynamic search for dropdown do you want this for the search as well?
- [ ] change border radius to 3px
   - for app canvas
   - for error messages
- [ ] use zippy to hide more vet information

Tracking changes to Style Guide Here: https://github.com/department-of-veterans-affairs/appeals-pm/issues/1056

**Comment by pkarman** [comment]
@carodew I am auditing tickets and found this one. Feel free to close if irrelevant.

**Comment by carodew** [comment]
oooh, a dinosaur issue! pinging @sneha-pai to see if she recognizes this and if not I think we can close it for lack of contextual knowledge.

**Comment by carodew** [comment]
closing due to lack of strenuous objection.
